object ModulesDep {

    const val assets = ":assets"
    const val navigation = ":navigations"
    const val data = ":data"
    const val domain = ":domain"
    const val common = ":common"
    const val sharedPref = ":library:sharedpref"
    const val apiResponse = ":model:apiresponse"
    const val entity = ":model:entity"
    const val di = ":core:di"
    const val api = ":core:api"
    const val cache = ":cache"

    const val login = ":feature-credential:login"
    const val verifyotp = ":feature-credential:verifyotp"
    const val registration = ":feature-credential:registration"
    const val profile = ":feature-common:profile"
    const val dashboard = ":feature-common:dashboard"
    const val editProfile = ":feature-common:editprofile"
    const val orderHistory = ":feature-common:orderhistory"
    const val address = ":feature-common:address"
    const val addAddress = ":feature-common:addaddress"
    const val product = ":feature-common:product"
    const val category = ":feature-common:category"
    const val cart = ":feature-common:cart"
    const val orderAddress = ":feature-common:orderaddress"
    const val payment = ":feature-common:payment"
    const val search = ":feature-common:search"
    const val orderDetails = ":feature-common:orderdetails"
    const val orderSuccess = ":feature-common:ordersuccess"
}